### ISSUE TITLE
Check lock files

### ISSUE THREAD

**Issue by dgdavid** [yast/the-installer#14]
At the time of writing, we have two lock files in the repo

* package-lock.json
* yarn.lock

I think we should evaluate if it is ok two keep them or just go for only one.

**Comment by dgdavid** [comment]
Looks like it is `npm v7` added support for _yarn.lock_ files 

* https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/#user-content-exciting-new-features
* https://blog.npmjs.org/post/621733939456933888/npm-v7-series-why-keep-package-lockjson


Thus, the npm CLI tool updates the _yarn.lock_ file when it is present. The fact that the former _installer-$80_ prototype [was created](https://github.com/imobachgs/installer-80/commit/12a7105b56adf8476d8fdb49b8d4dd31c6533fa5#diff-428679bb7ca62630fea052aff630a24fa13eaa2be9d1c45502b55c9fb2115010) with [create-react-app](https://create-react-app.dev/), which was [defaulting to yarn if installed](https://github.com/facebook/create-react-app/pull/11322), explains the presence of the file in this repo. The _package-lock.json_, however, was introduced [later](https://github.com/imobachgs/installer-80/commit/d873e4d57ca854a7165af690650f0be4c05edfdc#diff-3ebf69f247f3231fd796e60555489b4a1ed684e3ad4cb0ace460a2ed07d53a95).


So, a matter of chose

- continue using both
- use only `yarn`
- use only `npm`

I'd avoid the first one, although I have no strong opinion between `yarn` or `npm` right now (read, no enough knowledge for choosing one or the other).

**Comment by imobachgs** [comment]
I agree. It would be nice to come up with a list of pros/cons before taking a decision. What do you think?

**Comment by dgdavid** [comment]
After reading a couple of articles, there is no a clear winner for our use case or even for the stage of the project. While back in the time `yarn` was way better because of security reasons, nowadays looks like `npm` has solved or improved those issues. `yarn` still being faster<sup>1</sup>... but I think this is not a problem right now. What is more, IMHO we should run a few tests with the project itself instead of relying on generic benchmark for that regard. 

So, taking into account that 

> ... npm comes preinstalled with Node, so there’s no need to install npm manually. In contrast, Yarn needs to be installed explicitly.

and the fact that the yarn.lock file was deleted in #16 I'd stick to `npm` by the time being.

Of course, we can re-evaluate the decision in the future and transition to `yarn` if some of its unique features becomes relevant for D-installer at certain point.

Some links

* https://docs.npmjs.com/cli/v8/commands/npm
* https://yarnpkg.com/
* https://www.sitepoint.com/yarn-vs-npm/
* https://phoenixnap.com/kb/yarn-vs-npm
  

---

<sup>1</sup> Although it is not clear, see https://pnpm.io/benchmarks
